### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by dfishburn** [XadillaX/json-formatter.vim#1]
My file contains the following:

```
{"0": [{"text":"10021647","desc":"QMNUM"},{"text":"V00000000110","desc":"AUFNR","nodes": [{"text": "0010","desc":"VORNR","nodes": []},]}]}
```

And after running the jjson command, nothing happens.  I would expect to see something like:

```
{
  "0": [
    {
      "text":"10021647",
      "desc":"QMNUM"
    },
    {
      "text":"V00000000110",
      "desc":"AUFNR",
      "nodes": [
        {
          "text": "0010",
          "desc":"VORNR",
          "nodes": []
        },
      ]
    }
  ]
}
```

But on a more simple json text it correctly formats it.

```
{"AUFNR":"000040001265","WERKS":"0101","VORNR":"0010","WO_OPNOTE_LTXT":"5"}
```

Becomes:

```
{
    "AUFNR": "000040001265",
    "WERKS": "0101",
    "VORNR": "0010",
    "WO_OPNOTE_LTXT": "5"
}
```

**Comment by XadillaX** [comment]
Emmmmm, the first one I think you had an excess comma inside of `"nodes": [ { blahblah }, ]`.

So strictly speaking, it's has a syntax error.

**Comment by dfishburn** [comment]
You are right, removing the excess comma formats the string correctly:

```
{
    "0": [
        {
            "text": "10021647",
            "desc": "QMNUM"
        },
        {
            "text": "V00000000110",
            "desc": "AUFNR",
            "nodes": [
                {
                    "text": "0010",
                    "desc": "VORNR",
                    "nodes": []
                }
            ]
        }
    ]
}
```

Though failing silently is kind of useless.

When I run JSHint, a split window is opened and I get this message:

```
docflow.json|1 col 134 warning  94| Unexpected comma.
```

The above is useful as it tells me there was an error and the exact location of the error.  Which allows me to quickly correct the issue and run the command again.

The json I am formatting is often thousands of characters, so pin pointing errors is usually the reason I am running this stuff.  Trying to debug problems.

I had a look at jjson.cmd and distilled the commands it was executing.  When using the -v (--vim-plugin-mode):

```
C:\Program Files\nodejs>node.exe "node_modules\jjson\bin\jjson.js" -v -f "C:\temp\docflow.json"
{"0": [{"text":"10021647","desc":"QMNUM"}, {"text":"V00000000110","desc":"AUFNR","nodes": [{"text": "0010","desc":"VORNR","nodes": []},]}]}
```

Without -v:

```
C:\Program Files\nodejs>node.exe "node_modules\jjson\bin\jjson.js"  -f "C:\temp\docflow.json"
Error occurred while parsing file: Unexpected token ]
```

The good news is you get a bit more information back, at least something to display to the user.

The JSLint output is more useful as it gives a location, but anything is better at this point.

So I am not sure which of this is your code vs. you just adding a wrapper around to call something that already exists.

Is it possible to augment?

I also added:

```
echo %ERRORLEVEL%
```

After each call and it was 0, which was also unforuntate.
In Vim, for my plugins I check:
`echo v:shell_error`

When they have to shell out and execute something to get feedback.  Just another idea based on the responses to the above.

**Comment by XadillaX** [comment]
Thanks a lot. Exactly, I don't very understand to write a `VimL` file. I don't know how to get whether the result is a JSON string or an error string. Do you know any way?

**Comment by dfishburn** [comment]
I will update your Vim plugin and send you the updates.  There are a few things all plugins should do to prevent double loading.  I also added some ability to customize paths from the .vimrc.

Can you tell me why an error message is returned when _not_ using -v, but no error is returned when using -v?  

Did you write any of this code?  I am trying to figure out what can be changed by you and what you cannot change.  That will help figure out different approaches.

I really need a JSON formatter, so am happy to help out on this.

**Comment by XadillaX** [comment]
Thanks very much! I'm glad to receive your push request.

**Comment by dfishburn** [comment]
I have finished my changes to the formatter and the Vim plugin.  I ended up making more changes to the npm module to make it more useful with error reporting and feedback.

How would you like me to send you the updates?

**Comment by XadillaX** [comment]
@dfishburn Sure of cause, you're welcome to make PRs!

**Comment by dfishburn** [comment]
Okay, I have never used github before.
So I created an account, forked both XadillaX/json-formatter.vim and XadillaX/jjson.  Created PRs (json-formatter#3, jjson#1)  for each of my changes (must be used together) and hopefully this has sent them.

**Comment by XadillaX** [comment]
#3
