### ISSUE TITLE
Improvements to jjson

### ISSUE THREAD

**Issue by dfishburn** [XadillaX/json-formatter.vim#4]
> Make sure you have node.js installed and then install module below:
> $ npm install jjson -g

I had to make a bunch of improvements to jjson to both format and look for errors.
I would like to submit a patch to it, but I am not certain where I get the code (in GitHub) for it.

All the other changes I have made to the plugin rely on those changes being in jjson.

Thanks,
David

**Comment by XadillaX** [comment]
Here's the repo of jjson: https://github.com/XadillaX/jjson
